name: Deploy API to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Connect and deploy
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          cd ~/Anime8-AI
          git pull origin master
          
          docker stop anime8 || true
          docker rm anime8 || true
          
          docker system prune -af
          
          docker build --no-cache -t anime8 .
          docker run -d -p 5000:5000 --name anime8 anime8
          EOF
