name: Deploy Python App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install dependencies locally (CI step)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy code to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.VPS_USER }}/anime8"

      - name: Setup virtualenv, run DB setup and restart App with Supervisor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/anime8
            # Si le virtualenv n'existe pas, le créer
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            # Exécuter le script de setup de la DB
            python3 db/setup.py
            sudo supervisorctl reread
            sudo supervisorctl update
            sudo supervisorctl restart anime8 || sudo supervisorctl start anime8
